prompt = input("Enter a new member: ")
file = open("/users/ahmedhussein/downloads/members.txt", "r")
members = file.readlines()
members.append(prompt)
file = open("/Users/ahmedhussein/Downloads/members.txt", "w")
members = file.writelines(members)
